packages:
  - 'functions/*'

catalog:
  '@aws-sdk/client-sesv2': 3.777.0
  '@cloudflare/vite-plugin': 1.0.5
  '@openauthjs/openauth': 0.4.3
  '@paralleldrive/cuid2': 2.2.2
  '@react-router/dev': 7.5.0
  '@react-router/fs-routes': 7.5.0
  '@tailwindcss/cli': 4.0.14
  '@tailwindcss/typography': 0.5.16
  '@tailwindcss/vite': 4.0.14
  '@types/node': 22.13.14
  '@types/react': 19.1.0
  '@types/react-dom': 19.1.2
  aws4fetch: 1.0.20
  daisyui: 5.0.12
  effect: 3.14.6
  hono: 4.7.5
  isbot: 5.1.26
  jsonc-parser: 3.3.1
  lucide: 0.485.0
  react: 19.1.0
  react-dom: 19.1.0
  react-router: 7.5.0
  shadcn: 2.4.0
  stripe: 17.7.0
  tailwindcss: 4.0.17
  typescript: 5.8.2
  vite: 6.2.5
  vite-tsconfig-paths: 5.1.4
  wrangler: 4.10.0
  zx: 8.4.1
